packages:
  - src
  - webview-ui
  - packages/build
  - packages/cloud
  - packages/config-eslint
  - packages/config-typescript
  - packages/core
  - packages/core-schemas
  - packages/ipc
  - packages/telemetry
  - packages/types

onlyBuiltDependencies:
  - '@tailwindcss/oxide'
  - '@vscode/vsce-sign'
  - '@vscode/sqlite3'
  - core-js
  - esbuild
  - keytar
  - puppeteer-chromium-resolver
